[package]
name = "common-config"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
common-base.workspace = true
humantime-serde.workspace = true
rskafka = "0.5"
serde.workspace = true
